/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 11.0.0 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "../../rtl/asr8/asr8.v:2" *)
module asr8(clk, rst, din, dout, addr);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  (* src = "../../rtl/asr8/asr8.v:8" *)
  input [2:0] addr;
  (* src = "../../rtl/asr8/asr8.v:4" *)
  input clk;
  (* src = "../../rtl/asr8/asr8.v:6" *)
  input [7:0] din;
  (* src = "../../rtl/asr8/asr8.v:7" *)
  output [7:0] dout;
  wire [7:0] \regarray[0] ;
  wire [7:0] \regarray[1] ;
  wire [7:0] \regarray[2] ;
  wire [7:0] \regarray[3] ;
  wire [7:0] \regarray[4] ;
  (* src = "../../rtl/asr8/asr8.v:2" *)
  wire [8:0] \regarray[5] ;
  (* src = "../../rtl/asr8/asr8.v:2" *)
  wire [8:0] \regarray[6] ;
  (* src = "../../rtl/asr8/asr8.v:2" *)
  wire [8:0] \regarray[7] ;
  (* src = "../../rtl/asr8/asr8.v:5" *)
  input rst;
  INVX1 _089_ (
    .A(addr[1]),
    .Y(_065_)
  );
  INVX1 _090_ (
    .A(addr[0]),
    .Y(_066_)
  );
  INVX1 _091_ (
    .A(addr[2]),
    .Y(_067_)
  );
  INVX1 _092_ (
    .A(\regarray[4] [0]),
    .Y(_068_)
  );
  INVX1 _093_ (
    .A(\regarray[5] [0]),
    .Y(_069_)
  );
  INVX1 _094_ (
    .A(\regarray[2] [0]),
    .Y(_070_)
  );
  INVX1 _095_ (
    .A(\regarray[7] [1]),
    .Y(_071_)
  );
  INVX1 _096_ (
    .A(\regarray[4] [1]),
    .Y(_072_)
  );
  INVX1 _097_ (
    .A(\regarray[2] [1]),
    .Y(_073_)
  );
  INVX1 _098_ (
    .A(\regarray[7] [2]),
    .Y(_074_)
  );
  INVX1 _099_ (
    .A(\regarray[4] [2]),
    .Y(_075_)
  );
  INVX1 _100_ (
    .A(\regarray[5] [2]),
    .Y(_076_)
  );
  INVX1 _101_ (
    .A(\regarray[2] [2]),
    .Y(_077_)
  );
  INVX1 _102_ (
    .A(\regarray[6] [3]),
    .Y(_078_)
  );
  INVX1 _103_ (
    .A(\regarray[4] [3]),
    .Y(_079_)
  );
  INVX1 _104_ (
    .A(\regarray[5] [3]),
    .Y(_080_)
  );
  INVX1 _105_ (
    .A(\regarray[2] [3]),
    .Y(_081_)
  );
  INVX1 _106_ (
    .A(\regarray[6] [4]),
    .Y(_082_)
  );
  INVX1 _107_ (
    .A(\regarray[4] [4]),
    .Y(_083_)
  );
  INVX1 _108_ (
    .A(\regarray[5] [4]),
    .Y(_084_)
  );
  INVX1 _109_ (
    .A(\regarray[2] [4]),
    .Y(_085_)
  );
  INVX1 _110_ (
    .A(\regarray[6] [5]),
    .Y(_086_)
  );
  INVX1 _111_ (
    .A(\regarray[4] [5]),
    .Y(_087_)
  );
  INVX1 _112_ (
    .A(\regarray[5] [5]),
    .Y(_088_)
  );
  INVX1 _113_ (
    .A(\regarray[2] [5]),
    .Y(_000_)
  );
  INVX1 _114_ (
    .A(\regarray[7] [6]),
    .Y(_001_)
  );
  INVX1 _115_ (
    .A(\regarray[4] [6]),
    .Y(_002_)
  );
  INVX1 _116_ (
    .A(\regarray[5] [6]),
    .Y(_003_)
  );
  INVX1 _117_ (
    .A(\regarray[2] [6]),
    .Y(_004_)
  );
  INVX1 _118_ (
    .A(\regarray[4] [7]),
    .Y(_005_)
  );
  INVX1 _119_ (
    .A(\regarray[5] [7]),
    .Y(_006_)
  );
  INVX1 _120_ (
    .A(\regarray[2] [7]),
    .Y(_007_)
  );
  AND2X1 _121_ (
    .A(addr[1]),
    .B(addr[0]),
    .Y(_008_)
  );
  AND2X1 _122_ (
    .A(addr[2]),
    .B(_008_),
    .Y(_009_)
  );
  NAND2X1 _123_ (
    .A(addr[2]),
    .B(_008_),
    .Y(_010_)
  );
  AND2X1 _124_ (
    .A(_067_),
    .B(_008_),
    .Y(_011_)
  );
  AOI22X1 _125_ (
    .A(\regarray[7] [0]),
    .B(_009_),
    .C(_011_),
    .D(\regarray[3] [0]),
    .Y(_012_)
  );
  NAND2X1 _126_ (
    .A(_065_),
    .B(addr[0]),
    .Y(_013_)
  );
  NAND3X1 _127_ (
    .A(_065_),
    .B(addr[0]),
    .C(addr[2]),
    .Y(_014_)
  );
  INVX1 _128_ (
    .A(_014_),
    .Y(_015_)
  );
  NAND2X1 _129_ (
    .A(addr[1]),
    .B(_066_),
    .Y(_016_)
  );
  NAND3X1 _130_ (
    .A(addr[1]),
    .B(_066_),
    .C(_067_),
    .Y(_017_)
  );
  OAI22X1 _131_ (
    .A(_069_),
    .B(_014_),
    .C(_017_),
    .D(_070_),
    .Y(_018_)
  );
  NOR3X1 _132_ (
    .A(addr[1]),
    .B(addr[0]),
    .C(addr[2]),
    .Y(_019_)
  );
  NAND2X1 _133_ (
    .A(\regarray[0] [0]),
    .B(_019_),
    .Y(_020_)
  );
  NAND3X1 _134_ (
    .A(_065_),
    .B(_066_),
    .C(addr[2]),
    .Y(_021_)
  );
  OAI21X1 _135_ (
    .A(_068_),
    .B(_021_),
    .C(_020_),
    .Y(_022_)
  );
  NOR2X1 _136_ (
    .A(_067_),
    .B(_016_),
    .Y(_023_)
  );
  NAND3X1 _137_ (
    .A(addr[1]),
    .B(_066_),
    .C(addr[2]),
    .Y(_024_)
  );
  NOR2X1 _138_ (
    .A(addr[2]),
    .B(_013_),
    .Y(_025_)
  );
  AOI22X1 _139_ (
    .A(\regarray[6] [0]),
    .B(_023_),
    .C(_025_),
    .D(\regarray[1] [0]),
    .Y(_026_)
  );
  NOR2X1 _140_ (
    .A(_018_),
    .B(_022_),
    .Y(_027_)
  );
  NAND3X1 _141_ (
    .A(_012_),
    .B(_026_),
    .C(_027_),
    .Y(dout[0])
  );
  NAND2X1 _142_ (
    .A(\regarray[0] [1]),
    .B(_019_),
    .Y(_028_)
  );
  OAI21X1 _143_ (
    .A(_073_),
    .B(_017_),
    .C(_028_),
    .Y(_029_)
  );
  AOI22X1 _144_ (
    .A(\regarray[3] [1]),
    .B(_011_),
    .C(_015_),
    .D(\regarray[5] [1]),
    .Y(_030_)
  );
  OAI22X1 _145_ (
    .A(_071_),
    .B(_010_),
    .C(_021_),
    .D(_072_),
    .Y(_031_)
  );
  AOI22X1 _146_ (
    .A(\regarray[6] [1]),
    .B(_023_),
    .C(_025_),
    .D(\regarray[1] [1]),
    .Y(_032_)
  );
  NOR2X1 _147_ (
    .A(_029_),
    .B(_031_),
    .Y(_033_)
  );
  NAND3X1 _148_ (
    .A(_030_),
    .B(_032_),
    .C(_033_),
    .Y(dout[1])
  );
  OAI22X1 _149_ (
    .A(_074_),
    .B(_010_),
    .C(_017_),
    .D(_077_),
    .Y(_034_)
  );
  OAI22X1 _150_ (
    .A(_076_),
    .B(_014_),
    .C(_021_),
    .D(_075_),
    .Y(_035_)
  );
  NOR2X1 _151_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  AOI22X1 _152_ (
    .A(\regarray[3] [2]),
    .B(_011_),
    .C(_019_),
    .D(\regarray[0] [2]),
    .Y(_037_)
  );
  AOI22X1 _153_ (
    .A(\regarray[6] [2]),
    .B(_023_),
    .C(_025_),
    .D(\regarray[1] [2]),
    .Y(_038_)
  );
  NAND3X1 _154_ (
    .A(_036_),
    .B(_037_),
    .C(_038_),
    .Y(dout[2])
  );
  AOI22X1 _155_ (
    .A(\regarray[7] [3]),
    .B(_009_),
    .C(_011_),
    .D(\regarray[3] [3]),
    .Y(_039_)
  );
  OAI22X1 _156_ (
    .A(_081_),
    .B(_017_),
    .C(_021_),
    .D(_079_),
    .Y(_040_)
  );
  AOI21X1 _157_ (
    .A(\regarray[0] [3]),
    .B(_019_),
    .C(_040_),
    .Y(_041_)
  );
  OAI22X1 _158_ (
    .A(_080_),
    .B(_014_),
    .C(_024_),
    .D(_078_),
    .Y(_042_)
  );
  AOI21X1 _159_ (
    .A(\regarray[1] [3]),
    .B(_025_),
    .C(_042_),
    .Y(_043_)
  );
  NAND3X1 _160_ (
    .A(_039_),
    .B(_041_),
    .C(_043_),
    .Y(dout[3])
  );
  AOI22X1 _161_ (
    .A(\regarray[0] [4]),
    .B(_019_),
    .C(_025_),
    .D(\regarray[1] [4]),
    .Y(_044_)
  );
  OAI22X1 _162_ (
    .A(_085_),
    .B(_017_),
    .C(_021_),
    .D(_083_),
    .Y(_045_)
  );
  AOI21X1 _163_ (
    .A(\regarray[7] [4]),
    .B(_009_),
    .C(_045_),
    .Y(_046_)
  );
  OAI22X1 _164_ (
    .A(_084_),
    .B(_014_),
    .C(_024_),
    .D(_082_),
    .Y(_047_)
  );
  AOI21X1 _165_ (
    .A(\regarray[3] [4]),
    .B(_011_),
    .C(_047_),
    .Y(_048_)
  );
  NAND3X1 _166_ (
    .A(_044_),
    .B(_046_),
    .C(_048_),
    .Y(dout[4])
  );
  AOI22X1 _167_ (
    .A(\regarray[7] [5]),
    .B(_009_),
    .C(_019_),
    .D(\regarray[0] [5]),
    .Y(_049_)
  );
  AOI22X1 _168_ (
    .A(\regarray[3] [5]),
    .B(_011_),
    .C(_025_),
    .D(\regarray[1] [5]),
    .Y(_050_)
  );
  OAI22X1 _169_ (
    .A(_088_),
    .B(_014_),
    .C(_024_),
    .D(_086_),
    .Y(_051_)
  );
  OAI22X1 _170_ (
    .A(_000_),
    .B(_017_),
    .C(_021_),
    .D(_087_),
    .Y(_052_)
  );
  NOR2X1 _171_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NAND3X1 _172_ (
    .A(_049_),
    .B(_050_),
    .C(_053_),
    .Y(dout[5])
  );
  OAI22X1 _173_ (
    .A(_001_),
    .B(_010_),
    .C(_017_),
    .D(_004_),
    .Y(_054_)
  );
  OAI22X1 _174_ (
    .A(_003_),
    .B(_014_),
    .C(_021_),
    .D(_002_),
    .Y(_055_)
  );
  NOR2X1 _175_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  AOI22X1 _176_ (
    .A(\regarray[3] [6]),
    .B(_011_),
    .C(_019_),
    .D(\regarray[0] [6]),
    .Y(_057_)
  );
  AOI22X1 _177_ (
    .A(\regarray[6] [6]),
    .B(_023_),
    .C(_025_),
    .D(\regarray[1] [6]),
    .Y(_058_)
  );
  NAND3X1 _178_ (
    .A(_056_),
    .B(_057_),
    .C(_058_),
    .Y(dout[6])
  );
  AOI22X1 _179_ (
    .A(\regarray[7] [7]),
    .B(_009_),
    .C(_019_),
    .D(\regarray[0] [7]),
    .Y(_059_)
  );
  AOI22X1 _180_ (
    .A(\regarray[6] [7]),
    .B(_023_),
    .C(_025_),
    .D(\regarray[1] [7]),
    .Y(_060_)
  );
  OAI22X1 _181_ (
    .A(_007_),
    .B(_017_),
    .C(_021_),
    .D(_005_),
    .Y(_061_)
  );
  NAND3X1 _182_ (
    .A(_067_),
    .B(\regarray[3] [7]),
    .C(_008_),
    .Y(_062_)
  );
  OAI21X1 _183_ (
    .A(_006_),
    .B(_014_),
    .C(_062_),
    .Y(_063_)
  );
  NOR2X1 _184_ (
    .A(_061_),
    .B(_063_),
    .Y(_064_)
  );
  NAND3X1 _185_ (
    .A(_059_),
    .B(_060_),
    .C(_064_),
    .Y(dout[7])
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _186_ (
    .CLK(clk),
    .D(din[0]),
    .Q(\regarray[0] [0]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _187_ (
    .CLK(clk),
    .D(din[1]),
    .Q(\regarray[0] [1]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _188_ (
    .CLK(clk),
    .D(din[2]),
    .Q(\regarray[0] [2]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _189_ (
    .CLK(clk),
    .D(din[3]),
    .Q(\regarray[0] [3]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _190_ (
    .CLK(clk),
    .D(din[4]),
    .Q(\regarray[0] [4]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _191_ (
    .CLK(clk),
    .D(din[5]),
    .Q(\regarray[0] [5]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _192_ (
    .CLK(clk),
    .D(din[6]),
    .Q(\regarray[0] [6]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _193_ (
    .CLK(clk),
    .D(din[7]),
    .Q(\regarray[0] [7]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _194_ (
    .CLK(clk),
    .D(\regarray[0] [0]),
    .Q(\regarray[1] [0]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _195_ (
    .CLK(clk),
    .D(\regarray[0] [1]),
    .Q(\regarray[1] [1]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _196_ (
    .CLK(clk),
    .D(\regarray[0] [2]),
    .Q(\regarray[1] [2]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _197_ (
    .CLK(clk),
    .D(\regarray[0] [3]),
    .Q(\regarray[1] [3]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _198_ (
    .CLK(clk),
    .D(\regarray[0] [4]),
    .Q(\regarray[1] [4]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _199_ (
    .CLK(clk),
    .D(\regarray[0] [5]),
    .Q(\regarray[1] [5]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _200_ (
    .CLK(clk),
    .D(\regarray[0] [6]),
    .Q(\regarray[1] [6]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _201_ (
    .CLK(clk),
    .D(\regarray[0] [7]),
    .Q(\regarray[1] [7]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _202_ (
    .CLK(clk),
    .D(\regarray[1] [0]),
    .Q(\regarray[2] [0]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _203_ (
    .CLK(clk),
    .D(\regarray[1] [1]),
    .Q(\regarray[2] [1]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _204_ (
    .CLK(clk),
    .D(\regarray[1] [2]),
    .Q(\regarray[2] [2]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _205_ (
    .CLK(clk),
    .D(\regarray[1] [3]),
    .Q(\regarray[2] [3]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _206_ (
    .CLK(clk),
    .D(\regarray[1] [4]),
    .Q(\regarray[2] [4]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _207_ (
    .CLK(clk),
    .D(\regarray[1] [5]),
    .Q(\regarray[2] [5]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _208_ (
    .CLK(clk),
    .D(\regarray[1] [6]),
    .Q(\regarray[2] [6]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _209_ (
    .CLK(clk),
    .D(\regarray[1] [7]),
    .Q(\regarray[2] [7]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _210_ (
    .CLK(clk),
    .D(\regarray[2] [0]),
    .Q(\regarray[3] [0]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _211_ (
    .CLK(clk),
    .D(\regarray[2] [1]),
    .Q(\regarray[3] [1]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _212_ (
    .CLK(clk),
    .D(\regarray[2] [2]),
    .Q(\regarray[3] [2]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _213_ (
    .CLK(clk),
    .D(\regarray[2] [3]),
    .Q(\regarray[3] [3]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _214_ (
    .CLK(clk),
    .D(\regarray[2] [4]),
    .Q(\regarray[3] [4]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _215_ (
    .CLK(clk),
    .D(\regarray[2] [5]),
    .Q(\regarray[3] [5]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _216_ (
    .CLK(clk),
    .D(\regarray[2] [6]),
    .Q(\regarray[3] [6]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _217_ (
    .CLK(clk),
    .D(\regarray[2] [7]),
    .Q(\regarray[3] [7]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _218_ (
    .CLK(clk),
    .D(\regarray[3] [0]),
    .Q(\regarray[4] [0]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _219_ (
    .CLK(clk),
    .D(\regarray[3] [1]),
    .Q(\regarray[4] [1]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _220_ (
    .CLK(clk),
    .D(\regarray[3] [2]),
    .Q(\regarray[4] [2]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _221_ (
    .CLK(clk),
    .D(\regarray[3] [3]),
    .Q(\regarray[4] [3]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _222_ (
    .CLK(clk),
    .D(\regarray[3] [4]),
    .Q(\regarray[4] [4]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _223_ (
    .CLK(clk),
    .D(\regarray[3] [5]),
    .Q(\regarray[4] [5]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _224_ (
    .CLK(clk),
    .D(\regarray[3] [6]),
    .Q(\regarray[4] [6]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _225_ (
    .CLK(clk),
    .D(\regarray[3] [7]),
    .Q(\regarray[4] [7]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _226_ (
    .CLK(clk),
    .D(\regarray[4] [0]),
    .Q(\regarray[5] [0]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _227_ (
    .CLK(clk),
    .D(\regarray[4] [1]),
    .Q(\regarray[5] [1]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _228_ (
    .CLK(clk),
    .D(\regarray[4] [2]),
    .Q(\regarray[5] [2]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _229_ (
    .CLK(clk),
    .D(\regarray[4] [3]),
    .Q(\regarray[5] [3]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _230_ (
    .CLK(clk),
    .D(\regarray[4] [4]),
    .Q(\regarray[5] [4]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _231_ (
    .CLK(clk),
    .D(\regarray[4] [5]),
    .Q(\regarray[5] [5]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _232_ (
    .CLK(clk),
    .D(\regarray[4] [6]),
    .Q(\regarray[5] [6]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _233_ (
    .CLK(clk),
    .D(\regarray[4] [7]),
    .Q(\regarray[5] [7]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _234_ (
    .CLK(clk),
    .D(\regarray[5] [0]),
    .Q(\regarray[6] [0]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _235_ (
    .CLK(clk),
    .D(\regarray[5] [1]),
    .Q(\regarray[6] [1]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _236_ (
    .CLK(clk),
    .D(\regarray[5] [2]),
    .Q(\regarray[6] [2]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _237_ (
    .CLK(clk),
    .D(\regarray[5] [3]),
    .Q(\regarray[6] [3]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _238_ (
    .CLK(clk),
    .D(\regarray[5] [4]),
    .Q(\regarray[6] [4]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _239_ (
    .CLK(clk),
    .D(\regarray[5] [5]),
    .Q(\regarray[6] [5]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _240_ (
    .CLK(clk),
    .D(\regarray[5] [6]),
    .Q(\regarray[6] [6]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _241_ (
    .CLK(clk),
    .D(\regarray[5] [7]),
    .Q(\regarray[6] [7]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _242_ (
    .CLK(clk),
    .D(\regarray[6] [0]),
    .Q(\regarray[7] [0]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _243_ (
    .CLK(clk),
    .D(\regarray[6] [1]),
    .Q(\regarray[7] [1]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _244_ (
    .CLK(clk),
    .D(\regarray[6] [2]),
    .Q(\regarray[7] [2]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _245_ (
    .CLK(clk),
    .D(\regarray[6] [3]),
    .Q(\regarray[7] [3]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _246_ (
    .CLK(clk),
    .D(\regarray[6] [4]),
    .Q(\regarray[7] [4]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _247_ (
    .CLK(clk),
    .D(\regarray[6] [5]),
    .Q(\regarray[7] [5]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _248_ (
    .CLK(clk),
    .D(\regarray[6] [6]),
    .Q(\regarray[7] [6]),
    .R(rst),
    .S(1'h1)
  );
  (* src = "../../rtl/asr8/asr8.v:14" *)
  DFFSR _249_ (
    .CLK(clk),
    .D(\regarray[6] [7]),
    .Q(\regarray[7] [7]),
    .R(rst),
    .S(1'h1)
  );
  assign \regarray[5] [8] = 1'h0;
  assign \regarray[6] [8] = 1'h0;
  assign \regarray[7] [8] = 1'h0;
endmodule
