/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 11.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "../../rtl/lfsr16/lfsr16.v:3" *)
module lfsr16(clk, rst, dout, seed);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* src = "../../rtl/lfsr16/lfsr16.v:4" *)
  input clk;
  (* src = "../../rtl/lfsr16/lfsr16.v:9" *)
  wire [15:0] data;
  (* src = "../../rtl/lfsr16/lfsr16.v:6" *)
  output [15:0] dout;
  (* src = "../../rtl/lfsr16/lfsr16.v:10" *)
  wire feedback;
  (* src = "../../rtl/lfsr16/lfsr16.v:5" *)
  input rst;
  (* src = "../../rtl/lfsr16/lfsr16.v:7" *)
  input [15:0] seed;
  INVX1 _35_ (
    .A(rst),
    .Y(_32_)
  );
  NAND2X1 _36_ (
    .A(_32_),
    .B(seed[6]),
    .Y(_31_)
  );
  OR2X1 _37_ (
    .A(rst),
    .B(seed[6]),
    .Y(_30_)
  );
  OR2X1 _38_ (
    .A(rst),
    .B(seed[5]),
    .Y(_28_)
  );
  OR2X1 _39_ (
    .A(rst),
    .B(seed[4]),
    .Y(_26_)
  );
  OR2X1 _40_ (
    .A(rst),
    .B(seed[3]),
    .Y(_24_)
  );
  OR2X1 _41_ (
    .A(rst),
    .B(seed[2]),
    .Y(_22_)
  );
  OR2X1 _42_ (
    .A(seed[1]),
    .B(rst),
    .Y(_20_)
  );
  OR2X1 _43_ (
    .A(rst),
    .B(seed[0]),
    .Y(_18_)
  );
  OR2X1 _44_ (
    .A(rst),
    .B(seed[15]),
    .Y(_16_)
  );
  OR2X1 _45_ (
    .A(rst),
    .B(seed[14]),
    .Y(_14_)
  );
  OR2X1 _46_ (
    .A(rst),
    .B(seed[13]),
    .Y(_12_)
  );
  OR2X1 _47_ (
    .A(rst),
    .B(seed[12]),
    .Y(_10_)
  );
  OR2X1 _48_ (
    .A(rst),
    .B(seed[11]),
    .Y(_08_)
  );
  OR2X1 _49_ (
    .A(rst),
    .B(seed[10]),
    .Y(_06_)
  );
  OR2X1 _50_ (
    .A(rst),
    .B(seed[9]),
    .Y(_04_)
  );
  OR2X1 _51_ (
    .A(rst),
    .B(seed[8]),
    .Y(_02_)
  );
  OR2X1 _52_ (
    .A(rst),
    .B(seed[7]),
    .Y(_00_)
  );
  XOR2X1 _53_ (
    .A(data[4]),
    .B(data[15]),
    .Y(_33_)
  );
  XNOR2X1 _54_ (
    .A(data[2]),
    .B(data[1]),
    .Y(_34_)
  );
  XNOR2X1 _55_ (
    .A(_33_),
    .B(_34_),
    .Y(feedback)
  );
  NAND2X1 _56_ (
    .A(_32_),
    .B(seed[7]),
    .Y(_01_)
  );
  NAND2X1 _57_ (
    .A(_32_),
    .B(seed[8]),
    .Y(_03_)
  );
  NAND2X1 _58_ (
    .A(_32_),
    .B(seed[9]),
    .Y(_05_)
  );
  NAND2X1 _59_ (
    .A(_32_),
    .B(seed[10]),
    .Y(_07_)
  );
  NAND2X1 _60_ (
    .A(_32_),
    .B(seed[11]),
    .Y(_09_)
  );
  NAND2X1 _61_ (
    .A(_32_),
    .B(seed[12]),
    .Y(_11_)
  );
  NAND2X1 _62_ (
    .A(_32_),
    .B(seed[13]),
    .Y(_13_)
  );
  NAND2X1 _63_ (
    .A(_32_),
    .B(seed[14]),
    .Y(_15_)
  );
  NAND2X1 _64_ (
    .A(_32_),
    .B(seed[15]),
    .Y(_17_)
  );
  NAND2X1 _65_ (
    .A(_32_),
    .B(seed[0]),
    .Y(_19_)
  );
  NAND2X1 _66_ (
    .A(seed[1]),
    .B(_32_),
    .Y(_21_)
  );
  NAND2X1 _67_ (
    .A(_32_),
    .B(seed[2]),
    .Y(_23_)
  );
  NAND2X1 _68_ (
    .A(_32_),
    .B(seed[3]),
    .Y(_25_)
  );
  NAND2X1 _69_ (
    .A(_32_),
    .B(seed[4]),
    .Y(_27_)
  );
  NAND2X1 _70_ (
    .A(_32_),
    .B(seed[5]),
    .Y(_29_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _71_ (
    .CLK(clk),
    .D(data[6]),
    .Q(data[7]),
    .R(_00_),
    .S(_01_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _72_ (
    .CLK(clk),
    .D(data[7]),
    .Q(data[8]),
    .R(_02_),
    .S(_03_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _73_ (
    .CLK(clk),
    .D(data[8]),
    .Q(data[9]),
    .R(_04_),
    .S(_05_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _74_ (
    .CLK(clk),
    .D(data[9]),
    .Q(data[10]),
    .R(_06_),
    .S(_07_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _75_ (
    .CLK(clk),
    .D(data[10]),
    .Q(data[11]),
    .R(_08_),
    .S(_09_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _76_ (
    .CLK(clk),
    .D(data[11]),
    .Q(data[12]),
    .R(_10_),
    .S(_11_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _77_ (
    .CLK(clk),
    .D(data[12]),
    .Q(data[13]),
    .R(_12_),
    .S(_13_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _78_ (
    .CLK(clk),
    .D(data[13]),
    .Q(data[14]),
    .R(_14_),
    .S(_15_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _79_ (
    .CLK(clk),
    .D(data[14]),
    .Q(data[15]),
    .R(_16_),
    .S(_17_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _80_ (
    .CLK(clk),
    .D(feedback),
    .Q(data[0]),
    .R(_18_),
    .S(_19_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _81_ (
    .CLK(clk),
    .D(data[0]),
    .Q(data[1]),
    .R(_20_),
    .S(_21_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _82_ (
    .CLK(clk),
    .D(data[1]),
    .Q(data[2]),
    .R(_22_),
    .S(_23_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _83_ (
    .CLK(clk),
    .D(data[2]),
    .Q(data[3]),
    .R(_24_),
    .S(_25_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _84_ (
    .CLK(clk),
    .D(data[3]),
    .Q(data[4]),
    .R(_26_),
    .S(_27_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _85_ (
    .CLK(clk),
    .D(data[4]),
    .Q(data[5]),
    .R(_28_),
    .S(_29_)
  );
  (* src = "../../rtl/lfsr16/lfsr16.v:12" *)
  DFFSR _86_ (
    .CLK(clk),
    .D(data[5]),
    .Q(data[6]),
    .R(_30_),
    .S(_31_)
  );
  assign dout = data;
endmodule
