/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 11.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "../../rtl/f_addr/full_adder.v:1" *)
module f_addr(x, y, z, f, g);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "../../rtl/f_addr/full_adder.v:5" *)
  output f;
  (* src = "../../rtl/f_addr/full_adder.v:6" *)
  output g;
  (* src = "../../rtl/f_addr/full_adder.v:8" *)
  wire [1:0] temp;
  (* src = "../../rtl/f_addr/full_adder.v:2" *)
  input x;
  (* src = "../../rtl/f_addr/full_adder.v:3" *)
  input y;
  (* src = "../../rtl/f_addr/full_adder.v:4" *)
  input z;
  INVX1 _3_ (
    .A(y),
    .Y(_0_)
  );
  NAND2X1 _4_ (
    .A(z),
    .B(x),
    .Y(_1_)
  );
  XNOR2X1 _5_ (
    .A(z),
    .B(x),
    .Y(_2_)
  );
  XNOR2X1 _6_ (
    .A(y),
    .B(_2_),
    .Y(f)
  );
  OAI21X1 _7_ (
    .A(_0_),
    .B(_2_),
    .C(_1_),
    .Y(g)
  );
  assign temp = { g, f };
endmodule
